# Generated by Django 4.0 on 2022-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heartrate',
            field=models.IntegerField(default=60),
        ),
    ]
