# Generated by Django 4.0 on 2022-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0003_alter_patient_age_alter_patient_heartrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
