# Generated by Django 4.0 on 2022-05-10 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0005_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartrate', models.IntegerField(default=60)),
                ('height', models.DecimalField(decimal_places=3, default=2.5, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=3, default=2.5, max_digits=5)),
                ('BP', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('pulse', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
            ],
        ),
    ]
