# Generated by Django 4.0 on 2022-05-10 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0006_vitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='heartrate',
        ),
        migrations.AddField(
            model_name='patient',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='office_app.patient'),
        ),
    ]
