# Generated by Django 4.0 on 2022-05-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0007_remove_patient_heartrate_patient_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
