# Generated by Django 4.0 on 2022-05-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0014_alter_patient_age_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
