# Generated by Django 4.0 on 2022-05-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0016_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/models'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prescription_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('next_appointment', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office_app.patient')),
            ],
        ),
    ]
