# Generated by Django 4.0 on 2022-05-13 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0017_alter_patient_options_alter_patient_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='vitals',
            options={'verbose_name_plural': 'Vitals'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_date',
        ),
    ]
