# Generated by Django 4.0 on 2022-05-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0020_doctors_patient_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ManyToManyField(blank=True, to='office_app.Doctors'),
        ),
    ]
