# Generated by Django 4.0 on 2022-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0021_alter_patient_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
