# Generated by Django 4.0 on 2022-05-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0022_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='consultation_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='prescription_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='registration_fee',
            field=models.FloatField(),
        ),
    ]
