# Generated by Django 4.0 on 2022-05-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0023_alter_bills_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
    ]
