# Generated by Django 4.0 on 2022-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0024_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
