# Generated by Django 4.0 on 2022-05-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0027_diagnosis_created_at_diagnosis_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='created_by',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='created_by',
            field=models.ManyToManyField(to='office_app.Doctors'),
        ),
    ]
