# Generated by Django 4.0 on 2022-05-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0028_remove_diagnosis_created_by_diagnosis_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='created_by',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office_app.doctors'),
        ),
    ]
