# Generated by Django 4.0 on 2022-05-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0029_remove_diagnosis_created_by_diagnosis_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_diagnosis', to='office_app.doctors'),
        ),
    ]
