# Generated by Django 4.0 on 2022-05-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0030_alter_diagnosis_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
