# Generated by Django 4.0 on 2022-05-18 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office_app', '0031_bills_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
